#!/bin/bash
IFS=$'\n'

MD5_PATH="$1"
RES_PATH="$2"
UNPACK_PATH="$3"

for LINE in `cat "$MD5_PATH"`; do
	MD5=`echo "$LINE" | sed 's| .*||'`
	FILEPATH=`echo "$LINE" | sed 's|[a-f0-9]*  \./||'`
	
	echo "$MD5 $FILEPATH"
	
	mkdir -p "$UNPACK_PATH/`dirname $FILEPATH`"
	touch "$UNPACK_PATH/$FILEPATH"
done
