#!/bin/bash
IFS=$'\n'

MD5_PATH="$1.md5"
RES_PATH="$1.res"
#UNPACK_PATH=`readlink -f "$2"`
UNPACK_PATH="$2"

for LINE in `cat "$MD5_PATH"`; do
	MD5=`echo "$LINE" | sed 's| .*||'`
	FILEPATH=`echo "$LINE" | sed 's|[a-f0-9]*  \./||'`
	
	echo "$MD5 $FILEPATH"
	
	mkdir -p "$UNPACK_PATH/`dirname $FILEPATH`"
	cp "$RES_PATH/$MD5" "$UNPACK_PATH/$FILEPATH"
done
